# 伺服器設定
server:
  host: '0.0.0.0'
  port: 5000
  timeout: 60  # 秒

# 日誌設定
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  directory: 'logs'
  max_size: 10485760  # 10MB
  backup_count: 5

# NTCIP設定
ntcip:
  retry_count: 5
  retry_delay: 1  # 秒
  max_frame_size: 1024  # bytes 